version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
